#page title
page_title                                : 人生笔记                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1625209452                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : cn                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/cn/app/id1625209452?platform=iphone                   # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://lifelog.iofree.xyz/docs/download/download.html                                 # Enter Google Play Store URL.
presskit_download_link                    :                                     # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/logo.png                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : 人生笔记         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : 免费                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : |
  支持添加视频，照片，实况，录音；丰富的富文本操作，支持相册日历，地图视角，时间线；支持生成分享图，导出PDF，源数据导出导入。
  无广告，重视隐私安全，数据本地离线存储，自动备份，永久保存。

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Allen
your_link                                 : https://iofree.xyz
your_city                                 :
email_address                             : admin@iofree.xyz
facebook_username                         :
instagram_username                        :
twitter_username                          : Allen_Xuxu
github_username                           :
youtube_username                          :


# Feature List                            Edit, add or remove features to be presented.
features                                  :
  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

img  : # 展示 feature 下面的截图
  - url                                  : assets/img/1.png
  - url                                  : assets/img/2.png
  - url                                  : assets/img/3.png
  - url                                  : assets/img/4.png
  - url                                  : assets/img/5.png
  - url                                  : assets/img/6.png
  - url                                  : assets/img/7.png
  - url                                  : assets/img/8.png
  - url                                  : assets/img/9.png
  - url                                  : assets/img/10.png

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
